linkPrefix = ''
# linkPrefix = '/numenta-web'  # integration/staging (gh-pages)

siteHost = 'Numenta.org'
siteTitle = 'Hierarchical Temporal Memory (HTM)'
description = 'Home of the HTM Community'
company = 'Numenta'

[contact]
  [contact.email]
    info = 'info@numenta.org'

[analytics]
  google = 'UA-40622508-1'
  pingdom = '55a7dbc8abe53dba666b928b'

[links]
  [links.out]  # external links
    papers = 'http://numenta.com/papers/'
    bami = 'http://numenta.com/biological-and-machine-intelligence/'
    com = 'http://numenta.com/'
    cortical = 'https://cortical.io/'
    github = 'https://github.com/numenta'
    communityGithub = 'https://github.com/htm-community'
    grok = 'https://grokstream.com/'
    forum = 'https://discourse.numenta.org/categories'
    meetup = 'https://www.meetup.com/Numenta-Platform-for-Intelligent-Computing-Events/'
    onintelligence = 'https://www.amazon.com/Intelligence-Jeff-Hawkins/dp/0805078533'
    youtube = 'https://www.youtube.com/c/NumentaOrg'
    latestSchool = 'https://www.youtube.com/watch?v=HTW2Q_UrkAw'
    latestSchoolThumb = 'https://i3.ytimg.com/vi/HTW2Q_UrkAw/mqdefault.jpg'

  [links.in]  # internal paths
    # main/home pseudo-single page
    home = '/'
    community = '/community/'
    htm = '/hierarchical-temporal-memory/'
    code = '/code/'
    # other site pages
    school = '/htm-school/'
    blog = '/blog/'
    conduct = '/licenses/conduct/'
    contrib = '/licenses/contrib/'
    implement = '/implementations/'
    license = '/licenses/'
    privacy = '/legal/privacy/'
    sitemap = '/sitemap/'
    terms = '/legal/terms/'
    trial = '/licenses/trial/'

[moments]
  post = 'YYYY/MM/DD'
  human = 'ddd, MMM DD, YYYY'
