linkPrefix = ''
# linkPrefix = '/numenta-web'  # integration/staging (gh-pages)

siteHost = 'Numenta.com'
siteTitle = ''
description = 'Leading the New Era of Machine Intelligence'
company = 'Numenta'

[contact]
  [contact.email]
    feedback = 'feedback@numenta.com'
    info = 'info@numenta.com'
    press = 'press@numenta.com'
    sales = 'sales@numenta.com'
    support = 'support@numenta.com'
  [contact.phone]
    fax = '650-369-8283'
    tel = '650-369-8282'

[analytics]
  google = 'UA-48460134-1'
  pingdom = '569029d1abe53daf465fa724'

[links]
  [links.out]  # external links
    # apps
    grokGet = 'http://grokstream.com/#pricing'
    geo = 'https://github.com/numenta/nupic.geospatial'
    rogue = 'https://github.com/numenta/nupic.rogue'
    # legal
    license = 'http://numenta.org/licenses/'
    patents = 'http://patft.uspto.gov/netacgi/nph-Parser?Sect1=PTO2&Sect2=HITOFF&p=1&u=%2Fnetahtml%2FPTO%2Fsearch-bool.html&r=0&f=S&l=50&TERM1=Numenta&FIELD1=ASNM&co1=AND&TERM2=&FIELD2=&d=PTXT'
    trial = 'http://numenta.org/licenses/trial/'
    # partners
    cortical = 'http://cortical.io'
    grok = 'http://grokstream.com'
    org = 'http://numenta.org'
    # social
    facebook = 'https://www.facebook.com/pages/Numenta/321559142118?ref=br_tf'
    linkedin = 'https://www.linkedin.com/company/numenta'
    map = 'http://maps.google.com/maps?q=791+Middlefield+Road,+Redwood+City,+CA+94063'
    twitter = 'https://twitter.com/numenta'
    youtube = 'https://www.youtube.com/user/numenta'

  [links.in]  # internal paths
    # main/home pseudo-single page
    home = '/'
    mission = '/mission-and-history/'
    neuro = '/neuroscience-research/'
    technology = '/machine-intelligence-technology/'
    opensource = '/open-source-community/'
    applications = '/applications/'
    partners = '/partners/'
    business = '/business-strategy-and-ip/'
    anomaly = '/anomaly-detection-benchmark/'
    resources = '/papers-videos-and-more/'
    careers = '/careers-and-team/'
    contact = '/contact/'
    # other site pages
    bami = '/biological-and-machine-intelligence/'
    blog = '/blog/'
    events = '/events/'
    htmstocks = '/htm-for-stocks/'
    htmstudio = '/htm-studio/'
    nab = '/numenta-anomaly-benchmark/'
    newsletter = '/newsletter/'
    papers = '/papers/'
    press = '/press/'
    privacy = '/legal/privacy/'
    sitemap = '/sitemap/'
    terms = '/legal/terms/'

[moments]
  post = 'YYYY/MM/DD'
  human = 'ddd, MMM DD, YYYY'
